import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
RUNBOOK_PATH = ROOT / "docs" / "real-model-runbook.json"
CAPTURE_PATH = ROOT / "docs" / "real-model-evidence-capture.json"
PREFLIGHT_PATH = ROOT / "docs" / "real-model-preflight.json"
TEMPLATE_PATH = ROOT / ".github" / "ISSUE_TEMPLATE" / "real_model_run_review.md"
OUTPUT_JSON_PATH = ROOT / "docs" / "real-model-run-request-pack.json"
OUTPUT_MD_PATH = ROOT / "docs" / "real-model-run-request-pack.md"


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def build_real_model_run_request_pack() -> dict[str, Any]:
    runbook = load_json(RUNBOOK_PATH)
    capture = load_json(CAPTURE_PATH)
    preflight = load_json(PREFLIGHT_PATH)
    template_text = TEMPLATE_PATH.read_text()
    repo_url = "https://github.com/sunnnn2005/data-quality-agent"
    evidence_links = {
        "runbook": f"{repo_url}/blob/main/docs/real-model-runbook.md",
        "capture_gate": f"{repo_url}/blob/main/docs/real-model-evidence-capture.md",
        "preflight": f"{repo_url}/blob/main/docs/real-model-preflight.md",
        "review_issue": f"{repo_url}/issues/new?template=real_model_run_review.md",
        "business_csv_template": f"{repo_url}/blob/main/.github/ISSUE_TEMPLATE/business_data_replay.md",
    }
    acceptance_conditions = [
        "OPENAI_API_KEY is configured locally but never printed or committed.",
        "Local FastAPI health check passes before capture.",
        "Capture is generated by scripts/capture_real_model_run.py.",
        "The run records a trace_id, model, prompt_version, model calls, tool calls, latency, token, and cost telemetry.",
        "The model selects at least two whitelisted tools before finalizing.",
        "The final report is attached and passes deterministic verification.",
        "The submitted public issue contains no credentials, raw prompts, raw production rows, or private customer data.",
        "The submitted public issue grants permission to count the evidence.",
    ]
    resume_unlocks = [
        {
            "metric": "real_model_runs",
            "current": capture["accepted_real_model_run_count"],
            "target": 1,
            "resume_claim_when_met": "Captured an accepted OpenAI-compatible LLM agent run with redacted public telemetry.",
        },
        {
            "metric": "real_model_tool_calling_runs",
            "current": capture["accepted_real_model_run_count"],
            "target": 1,
            "resume_claim_when_met": "Demonstrated real model tool selection across multiple controlled data-quality tools.",
        },
        {
            "metric": "real_model_verified_reports",
            "current": capture["accepted_real_model_run_count"],
            "target": 1,
            "resume_claim_when_met": "Produced a verified structured data-quality report from a real LLM agent run.",
        },
        {
            "metric": "real_model_cost_tracked_runs",
            "current": capture["accepted_real_model_run_count"],
            "target": 1,
            "resume_claim_when_met": "Tracked latency, token usage, and estimated cost for a real LLM agent run.",
        },
    ]
    template_checks = {
        "has_run_path": "## Run path" in template_text,
        "has_redacted_telemetry": "## Redacted telemetry" in template_text,
        "has_tool_evidence": "## Tool evidence" in template_text,
        "has_permission_boundary": "## Permission and privacy" in template_text,
        "blocks_credentials": "no provider credentials" in template_text.lower(),
        "blocks_raw_prompts": "raw prompts" in template_text.lower(),
        "requires_count_permission": "You may count this public issue" in template_text,
    }
    return {
        "project": "Data Quality Agent",
        "generated_by": "scripts/build_real_model_run_request_pack.py",
        "purpose": "Create a public, privacy-safe request path for collecting accepted real LLM agent run evidence.",
        "current_real_model_runs": capture["accepted_real_model_run_count"],
        "preflight_status": preflight["real_model_execution_status"],
        "run_command_count": runbook["run_command_count"],
        "capture_required_field_count": capture["capture_required_field_count"],
        "evidence_link_count": len(evidence_links),
        "evidence_links": evidence_links,
        "acceptance_condition_count": len(acceptance_conditions),
        "acceptance_conditions": acceptance_conditions,
        "resume_unlock_count": len(resume_unlocks),
        "resume_unlocks": resume_unlocks,
        "template": str(TEMPLATE_PATH.relative_to(ROOT)),
        "template_checks": template_checks,
        "claimable_now": [],
        "resume_status": "real_model_request_ready_not_claimable",
        "resume_safe_summary": (
            "Published a real-model run request pack with a privacy-safe issue template, 5 evidence links, "
            "8 acceptance conditions, and 4 resume unlocks that remain blocked until an accepted redacted "
            "OpenAI-compatible agent trace exists."
        ),
        "not_claimed": [
            "accepted real model run",
            "real model tool-calling benchmark",
            "provider credential value",
            "raw prompt contents",
            "raw business rows",
        ],
    }


def render_markdown(payload: dict[str, Any]) -> str:
    links = "\n".join(
        f"- {key.replace('_', ' ').title()}: [{url}]({url})" for key, url in payload["evidence_links"].items()
    )
    conditions = "\n".join(f"- {item}" for item in payload["acceptance_conditions"])
    unlocks = "\n".join(
        "| {metric} | {current} | {target} | {claim} |".format(
            metric=item["metric"],
            current=item["current"],
            target=item["target"],
            claim=item["resume_claim_when_met"],
        )
        for item in payload["resume_unlocks"]
    )
    checks = "\n".join(f"| {key.replace('_', ' ').title()} | {value} |" for key, value in payload["template_checks"].items())
    not_claimed = "\n".join(f"- {item}" for item in payload["not_claimed"])
    return f"""# Real Model Run Request Pack

This generated artifact turns a real OpenAI-compatible LLM agent run into a privacy-safe public evidence path.

## Current Status

| Metric | Value |
| --- | ---: |
| Current real model runs | {payload["current_real_model_runs"]} |
| Preflight status | `{payload["preflight_status"]}` |
| Run commands | {payload["run_command_count"]} |
| Capture required fields | {payload["capture_required_field_count"]} |
| Resume unlocks | {payload["resume_unlock_count"]} |

## Evidence Links

{links}

## Acceptance Conditions

{conditions}

## Resume Unlocks

| Metric | Current | Target | Resume claim when met |
| --- | ---: | ---: | --- |
{unlocks}

## Template Checks

| Check | Passed |
| --- | --- |
{checks}

## Resume-Safe Summary

{payload["resume_safe_summary"]}

## Not Claimed

{not_claimed}
"""


def verify_real_model_run_request_pack(payload: dict[str, Any]) -> dict[str, Any]:
    if payload["current_real_model_runs"] != 0:
        raise AssertionError("request pack must preserve zero real-model-run baseline")
    if payload["evidence_link_count"] != 5:
        raise AssertionError("request pack must expose five evidence links")
    if payload["acceptance_condition_count"] != 8:
        raise AssertionError("request pack must define eight acceptance conditions")
    if payload["resume_unlock_count"] != 4:
        raise AssertionError("request pack must define four resume unlocks")
    if payload["capture_required_field_count"] != 17:
        raise AssertionError("request pack must reflect the 17-field capture gate")
    if payload["claimable_now"] != []:
        raise AssertionError("request pack must not claim real model evidence before an accepted run")
    if not all(payload["template_checks"].values()):
        raise AssertionError("real model run issue template is missing required sections")
    joined = json.dumps(payload, sort_keys=True).lower()
    for required in (
        "openai-compatible",
        "tool",
        "trace",
        "latency",
        "token",
        "cost",
        "verification",
        "permission",
        "raw prompt",
        "raw business rows",
    ):
        if required not in joined:
            raise AssertionError(f"request pack missing required concept: {required}")
    return {
        "real_model_run_request_pack_verified": True,
        "acceptance_condition_count": payload["acceptance_condition_count"],
        "resume_unlock_count": payload["resume_unlock_count"],
        "current_real_model_runs": payload["current_real_model_runs"],
    }


def main() -> None:
    payload = build_real_model_run_request_pack()
    verify_real_model_run_request_pack(payload)
    OUTPUT_JSON_PATH.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    OUTPUT_MD_PATH.write_text(render_markdown(payload))
    print(json.dumps(payload, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
